version: '3.4'

services:
  monocle:
    image: ${DOCKER_REGISTRY-}monocle
    build:
      context: ..
      dockerfile: src/Monocle/Dockerfile
    volumes:
      - type: bind
        source: ./Monocle/db
        target: /app/db
